USE proje;
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'StrongKeyPass';

CREATE CERTIFICATE TDECert WITH SUBJECT = 'TDE Certificate';

USE proje;
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE TDECert;

ALTER DATABASE proje SET ENCRYPTION ON;
